[package]
name = "aoc"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
rayon = "1.10.0"
regex = "1.11.1"
