[package]
name = "aoc2024"
version = "0.8.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
aoc = { path = "../aoc" }
logos = "0.14.3"
